<html>
<head>
    <title>@yield('title')</title>
</head>
<body>
    <h1>@yield('title')</h1>
    <h2>@yield('title')</h2>
    @section('menubar')
    <h2>メニュー</h2>
    <h3>@yield('wasshoi')</h3>
    <ul>
        <li>@show</li>
    </ul>
    <hr>
    <div>
        @yield('content')
    </div>
    <div>
        @yield('footer')
    </div>
</body>
</html>